---
# Prerequisites for Oracle RAC Installation

- name: Install required packages
  yum:
    name: "{{ required_packages }}"
    state: present
  tags: packages

- name: Set authorized key for root
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  tags: ssh_keys

- name: Clean yum cache
  command: yum clean all
  tags: cleanup

- name: Link Python3 to Python
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    owner: root
    group: root
    state: link
  tags: python_link

- name: Ensure SELinux is in permissive mode
  selinux:
    policy: targeted
    state: permissive
  tags: selinux

- name: Configure hosts file
  template:
    src: templates/hosts.j2
    dest: /etc/hosts
    backup: yes
  tags: hosts_file

- name: Configure Oracle limits
  copy:
    dest: /etc/security/limits.d/90-nproc.conf
    content: |
      # Oracle recommended limits
      oracle soft nproc 2047
      oracle hard nproc 16384
      oracle soft nofile 1024
      oracle hard nofile 65536
      oracle soft stack 10240
      oracle hard stack 32768
      grid soft nproc 2047
      grid hard nproc 16384
      grid soft nofile 1024
      grid hard nofile 65536
      grid soft stack 10240
      grid hard stack 32768
  tags: oracle_limits

- name: Configure kernel parameters
  copy:
    dest: /etc/security/limits.conf
    content: |
      # Oracle kernel parameters
      oracle soft nproc 2047
      oracle hard nproc 16384
      oracle soft nofile 1024
      oracle hard nofile 65536
      oracle soft stack 10240
      oracle hard stack 32768
      grid soft nproc 2047
      grid hard nproc 16384
      grid soft nofile 1024
      grid hard nofile 65536
      grid soft stack 10240
      grid hard stack 32768
    backup: yes
  tags: kernel_params

- name: Apply kernel parameters
  command: sysctl -p
  tags: kernel_apply

- name: Start and enable tuned service
  systemd:
    state: started
    enabled: yes
    name: tuned.service
  tags: tuned

- name: Activate Oracle tuned profile
  command: tuned-adm profile oracle
  tags: tuned_profile

- name: Update GRUB configuration
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  tags: grub_update

- name: Add Oracle GPG key
  rpm_key:
    key: https://yum.oracle.com/RPM-GPG-KEY-oracle-ol8
    state: present
  tags: gpg_key

- name: Install Oracle ASM kernel module
  dnf:
    name: kmod-oracleasm
    state: present
  tags: kmod_oracleasm

- name: Install Oracle ASM support
  dnf:
    name: "{{ oracle_software_urls.oracleasm_support }}"
    state: present
  tags: oracleasm_support

- name: Install CVU disk utility
  dnf:
    name: "{{ oracle_software_urls.cvuqdisk }}"
    disable_gpg_check: true
    state: present
  tags: cvuqdisk

- name: Install Oracle ASM library
  dnf:
    name: "{{ oracle_software_urls.oracleasmlib }}"
    state: present
  tags: oracleasmlib

- name: Install Oracle database preinstall package
  dnf:
    name: "{{ oracle_software_urls.oracle_preinstall }}"
    state: present
  tags: oracle_preinstall

- name: Configure chrony
  template:
    src: templates/chrony.conf.j2
    dest: /etc/chrony.conf
    backup: yes
  notify: restart chronyd
  tags: chrony_config

- name: Set timezone
  command: timedatectl set-timezone Europe/Prague
  tags: timezone

- name: Start and enable chrony service
  systemd:
    name: chronyd
    state: started
    enabled: yes
  tags: chrony_service

- name: Configure system profile for Oracle
  template:
    src: templates/oracle_profile.j2
    dest: /etc/profile
    backup: yes
  tags: system_profile

- name: Reboot nodes after configuration
  reboot:
    msg: "Reboot initiated by Ansible for Oracle RAC setup"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  tags: reboot 