---
# Storage Configuration for Oracle RAC

- name: Configure iSCSI initiator
  template:
    src: templates/initiatorname.iscsi.j2
    dest: /etc/iscsi/initiatorname.iscsi
    backup: yes
  tags: iscsi_config

- name: Start and enable iSCSI service
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - iscsi
    - iscsid
  tags: iscsi_service

- name: Discover iSCSI targets
  command: "iscsiadm -m discovery -t sendtargets -p {{ iscsi_target_ip }}"
  register: iscsi_discovery
  changed_when: "'New discovery record' in iscsi_discovery.stdout"
  tags: iscsi_discovery

- name: Login to iSCSI targets
  command: iscsiadm -m node -l
  register: iscsi_login
  changed_when: "'successful' in iscsi_login.stdout"
  tags: iscsi_login

- name: Run ASM driver configureation
  become: yes
  become_user: root
  shell: |
    spawn oracleasm configure -i
     sleep 5
     expect "\[Default user to own the driver interface []:\n" 
     send -- "grid\r"
     expect "\[Default group to own the driver interface []:]\n" 
     send -- "dba\r"
     expect "\[Scan for Oracle ASM disks on boot (y/n):]\n"
     send -- "y\r"
     expect "\[Writing Oracle ASM library driver configuration: done]\n"
     send -- "\r"
     expect eof

  args: 
    executable: /usr/bin/expect

- name: Create partition for OCR/VOTING disk
  parted:
    device: "{{ asm_disks.ocr_voting }}"
    number: 1
    state: present
  tags: ocr_partition

- name: Create ASM OCR_VOTING disk
  command: "oracleasm createdisk OCR_VOTING {{ asm_disks.ocr_voting }}1"
  register: asm_ocr_create
  changed_when: "'Writing disk header' in asm_ocr_create.stdout"
  failed_when: 
    - asm_ocr_create.rc != 0
    - "'already labeled' not in asm_ocr_create.stderr"
    - "'already labeled' not in asm_ocr_create.stdout"
  tags: asm_ocr_disk

- name: Create partition for DATA disk
  parted:
    device: "{{ asm_disks.data }}"
    number: 1
    state: present
  tags: data_partition

- name: Create ASM DATA disk
  command: "oracleasm createdisk DATA {{ asm_disks.data }}1"
  register: asm_data_create
  changed_when: "'Writing disk header' in asm_data_create.stdout"
  failed_when: 
    - asm_data_create.rc != 0
    - "'already labeled' not in asm_data_create.stderr"
    - "'already labeled' not in asm_data_create.stdout"
  tags: asm_data_disk

- name: Create partition for FRA disk
  parted:
    device: "{{ asm_disks.fra }}"
    number: 1
    state: present
  tags: fra_partition

- name: Create ASM FRA disk
  command: "oracleasm createdisk FRA {{ asm_disks.fra }}1"
  register: asm_fra_create
  changed_when: "'Writing disk header' in asm_fra_create.stdout"
  failed_when: 
    - asm_fra_create.rc != 0
    - "'already labeled' not in asm_fra_create.stderr"
    - "'already labeled' not in asm_fra_create.stdout"
  tags: asm_fra_disk

- name: Initialize ASM
  command: oracleasm init
  register: asm_init
  changed_when: "'Loading module' in asm_init.stdout or 'Configuring' in asm_init.stdout"
  tags: asm_init

- name: Scan for ASM disks
  command: oracleasm scandisks
  tags: asm_scan

- name: Check if ASM disks directory exists
  stat:
    path: /dev/oracleasm/disks
  register: asm_disks_dir
  tags: asm_permissions

- name: Set ASM disk permissions
  shell: chown -R grid:dba /dev/oracleasm/disks/*
  when: asm_disks_dir.stat.exists and asm_disks_dir.stat.isdir
  ignore_errors: yes
  tags: asm_permissions

- name: List ASM disks
  command: oracleasm listdisks
  register: asm_list
  tags: asm_list

- name: Display current ASM disks
  debug:
    var: asm_list.stdout_lines
  tags: asm_list 
